# Generated by Django 4.2.3 on 2025-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studentprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(upload_to='mysite/myapp/static/profile_images/'),
        ),
    ]
