# Generated by Django 4.2.3 on 2025-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_studentprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(upload_to='../static/profile_images/'),
        ),
    ]
